spring:

  application:
    name: product-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://mysql1:3307/product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: user1234

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

